config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  get '/home', to: 'tweets#home', as: :tweet_root_path

  resources :users, only: %i[show]

  resources :users do
    member do
      patch :follow
    end
  end

  resources :tweets, only: %i[create update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'user_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'

  has_many :followed_tweets, through: :following, source: :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :replies, class_name: "Tweet", foreign_key: "source_id"
  belongs_to :source, class_name: "Tweet", optional: true

  validates :content, presence: true
  validates :content, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
  has_many :followings, through: :following_relationships, source: :following

  has_many :followed_tweets, through: :follows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    tweet_root_path_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def home
    @tweets = current_user.followed_tweets.order(Arel.sql('RANDOM()')).limit(10)
    @tweet = Tweet.new
    if params[:keyword].present?
      @search_news = News::Search.by_keyword(params[:keyword])['articles']
      respond_to do |format|
        format.js { render partial: 'search-results'}
      end
    else
      @news = News::Search.headlines['articles']
    end
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      redirect_to tweet_root_path_url
    else
      @tweets = current_user.followed_tweets.order(Arel.sql('RANDOM()')).limit(10)
      render :home
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.likes_count.nil?
      @tweet.likes_count = 1
    else
      @tweet.likes_count += 1
    end
    redirect_to tweet_root_path_url(anchor: "tweet-#{@tweet.id}") if @tweet.save
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %I[show follow]

  def show
  end

  def follow
    current_user.followings << @user
    render :show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  # def resource_class
  #   User
  # end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background-photo">        
  <div class="container">
    <div class="row">
      <div class="col-4">
        <div class="landing-page-banner">          
          <%= image_tag("logo-dark.png", size: "350x300") %>          
          <div class="landing-page-links">
            <button type="button" class="btn btn-signup mt-4 mr-3" data-toggle="modal" data-target=".signup-form">Sign Up</button>
            <button type="button" class="btn btn-login mt-4" data-toggle="modal" data-target=".login-form">Log in</button>
          </div>
        </div>        
      </div>
      <div class="col-8 footer-box">
        <div class="landing-page-footer">          
          <%= link_to "About", "#", class: "mx-1" %>
          <%= link_to "Terms of Service", "#", class: "mx-1" %>
          <%= link_to "Privacy Policy", "#", class: "mx-1" %>
          <%= link_to "Cookie Policy", "#", class: "mx-1" %>
          <%= link_to "Developers", "#", class: "mx-1" %>
          <%= link_to "Directory", "#", class: "mx-1" %>
          <%= link_to "Settings", "#", class: "mx-1" %>          
        </div>
      </div>
      <div class="modal fade signup-form" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <%= render file: "devise/registrations/new" %>
          </div>
        </div>
      </div>
      <div class="modal fade login-form" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <%= render file: "devise/sessions/new" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_buttons.html.erb
<a class="btn btn-tweet" href="#">Tweet</a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_user == true %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/tweets/_results.html.erb
<% @search_news.each do |n| %>
  <%= link_to  "#{n['url']}", class: "news-link" do %>
    <div class="news">
      <div class="news-info d-flex justify-content-between">
        <div>
          <h4><%= n['title'] %></h4>
          <p id="news-author"><em><%= n['author'] %></em></p>
        </div>
        <%= image_tag "#{n['urlToImage']}", class: "news-img" %>
      </div>
      <p><%= n['description'] %></p>
    </div>
  <% end %>
<% end %>

app/views/tweets/_search-results.js.erb
$(".news").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/tweets/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-0 col-lg-3">
      <div class="nav-menu">
        <%= image_tag("logo.png", size: "150x150", class: "mt-3 ml-4") %>
        <div class="nav-menu-links align-items-center">          
          <%= link_to tweet_root_path_path, class: "btn btn-nav-menu mb-1" do %><i class="fas fa-home mr-4" target="_blank"></i>Home<% end %><br>
          <%= link_to "#", class: "btn btn-nav-menu mb-1" do %><i class="fas fa-hashtag mr-4" target="_blank"></i>Explore<% end %><br>
          <%= link_to "#", class: "btn btn-nav-menu mb-1" do %><i class="fas fa-bell mr-4" target="_blank"></i>Notifications<% end %><br>
          <%= link_to "#", class: "btn btn-nav-menu mb-1" do %><i class="fas fa-envelope mr-4" target="_blank"></i>Messages<% end %><br>
          <%= link_to "#", class: "btn btn-nav-menu mb-1" do %><i class="fas fa-bookmark mr-4" target="_blank"></i>Bookmarks<% end %><br>
          <%= link_to user_path(current_user), class: "btn btn-nav-menu mb-3" do %><i class="fas fa-user-circle mr-4" target="_blank"></i>Profile<% end %><br>          
          <%= link_to "Spark", "#", class: "btn btn-tweet w-100" %>
        </div>
        <div class="log-out">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-signup px-3" %>
        </div>
      </div>    
    </div>
    <div class="col-12 col-lg-6">
      <div class="row">
        <div class="col-12">
          <h3 class="home-title">Home</h3>
        </div>
        <div class="col-12">
          <div class="new-tweet-form">
            <%= simple_form_for([@tweet], remote: true) do |f| %>
              <%= f.input :content, label: false, placeholder: "What's happening?" %>
              <div class="d-flex justify-content-end">
                <%= f.submit 'Spark', class: 'btn btn-tweet' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <% @tweets.each do |tweet| %>
            <div class="tweet" id="tweet-<%= tweet.id %>">
              <% if tweet.is_retweet %>
                <div class="retweet d-flex">
                  <i class="fas fa-retweet"></i>
                  <%= tweet.user.username %> Retweeted
                </div>
              <% end %>
              <div class="tweet-info d-flex">
                <%= link_to user_path(tweet.user), class: 'user-avatar' do %>
                    <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar"%>
                <% end %>
                <div class="tweet-content w-75">
                  <div class="user-info d-flex">
                    <%= link_to user_path(tweet.user), class: 'd-flex user-info-link' do %>
                      <p class="user-info-username"><%= tweet.user.username %></p>
                      <p>@<%= tweet.user.user_account %></p>
                    <% end %>
                    <p> - <%= ((Time.now - tweet.created_at)/3600).ceil %>h</p>
                  </div>
                  <p class="tweet-content-text"><%= tweet.content %></p>
                  <div class="tweet-actions d-flex justify-content-between">
                    <div class="tweet-reply">
                      <i class="far fa-comment-dots"></i> <%= tweet.replies_count %>
                    </div>
                    <div class="tweet-retweet">
                      <i class="fas fa-retweet"></i> <%= tweet.retweets_count %>
                    </div>
                    <div class="tweet-like">
                      <%= link_to tweet_path(tweet), method: :patch, remote: true do %>
                        <i class="fas fa-heart"></i> <span ><%= tweet.likes_count %></span>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-0 col-lg-3">
      <h3 id="top-news-title">What's happening</h3>
        <%= form_with url: "/home", method: "get", remote: true do |f| %>
        <%= f.text_field :keyword, placeholder: "Search for news", class: "form-control search-news" %>
        <%= f.submit "Search", class: "btn btn-primary search-news-button" %>
      <% end %>
      <div id="search-results">
      </div>
      <% @news.each do |n| %>
        <%= link_to  "#{n['url']}", class: "news-link" do %>
          <div class="news">
            <div class="news-info d-flex justify-content-between">
              <div>
                <h4><%= n['title'] %></h4>
                <p id="news-author"><em><%= n['author'] %></em></p>
              </div>
              <%= image_tag "#{n['urlToImage']}", class: "news-img" %>
            </div>
            <p><%= n['description'] %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-0 col-lg-3"></div>
    <div class="col-12 col-lg-6">
      <div class="user">
        <div class="user-header d-flex align-items-center">
          <%= link_to tweet_root_path_url do %>
            <i class="fas fa-arrow-left"></i>
          <% end %>
          <div class="ml-3">
            <h3><%= @user.username %></h3>
            <p><%= @user.tweets.count %> Tweets</p>
          </div>
        </div>
        <div class="user-banner">
          <%= image_tag 'https://images.unsplash.com/photo-1616424285354-3057203b5f44?ixid=MXwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxM3x8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60' %>
        </div>
        <div class="user-profile-avatar">
          <%= image_tag 'avatar-placeholder' %>
        </div>
        <div class="user-infos">
          <div class="user-infos-1 d-flex justify-content-between align-items-center">
            <div>
              <h3><%= @user.username %></h3>
              <p>@<%= @user.user_account %></p>
            </div>
            <% if current_user.followings.include? @user %>
              <div id="followed-button">Followed</div>
            <% else %>
              <%= link_to 'Follow', follow_user_path(@user), remote: true, method: :patch %>
            <% end %>
          </div>
          <p><%= @user.bio %></p>
          <div class="user-infos-2 d-flex">
            <p class="mr-3"><i class="fas fa-map-marker-alt mr-1"></i><%= @user.location %></p>
            <p><i class="fas fa-calendar-alt mr-1"></i> Joined <%= @user.created_at.strftime('%B %Y') %></p>
          </div>
          <div class="user-infos-3 d-flex">
            <p class="mr-3"><span><%= @user.followings.count %></span> Following</p>
            <p><span><%= @user.followers.count %></span> Followers</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-0 col-lg-3"></div>
  </div>
</div>